# Waypoint Lookup

string waypoint_name         # Name of waypoints to look up
---
bool success                 # True if waypoint found, False otherwise
CombinedJointPoint waypoint  # Requested waypoint
