# Waypoint Lookup

string waypoint_name         # Name of waypoints to look up
---
bool result                  # True if waypoint found, False otherwise
CombinedJointPoint waypoint  # Requested waypoint
